# Initial build container. Contains 500mb of build dependencies and make
    FROM armhf/alpine
    RUN apk update && apk add clang git cmake make bash build-base perl
    RUN git clone --recursive https://github.com/cuberite/cuberite.git
    RUN apk --no-cache add ca-certificates wget
    RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub
    RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-2.25-r0.apk
    RUN apk add glibc-2.25-r0.apk
    RUN apk del musl
    RUN   cd cuberite && \
          cmake . -DCMAKE_BUILD_TYPE=RELEASE && \
          make -j 4
    COPY /cuberite/Server .

# Build the final container by moving over the build artifacts
    FROM armhf/alpine
    EXPOSE 25565 25566
    RUN apk add --update libstdc++
    COPY --from=0 /cuberite/Server /cuberite/Server
    CMD ["./cuberite/Server/Cuberite"]
