# docker run -d --restart=always \
#   --name=plexpy \
#   -v /tmp/plexpy/config:/config \
#   -v /tmp/plexpy/logs:/logs:ro \
#   -e PGID=901 -e PUID=901  \
#   -e TZ="New York" \
#   -p 8181:83 \
#   linuxserver/plexpy
