###############################################################################
#
#      HomeAssistant.io is a home automation program with a nice GUI
#
###############################################################################
FROM armhf/alpine

ENV HOME=/home/homeassistant

EXPOSE 8123

VOLUME /config

RUN \
apk update && \
apk upgrade && \
apk add \
 bash \
 python3 \
 py-pip \
 gcc \
 make \
 musl-dev \
 git \
 openssl-dev \
 libffi-dev && \
 rm -rf /var/cache/apk/*

RUN \
pip install --upgrade pip && \
pip install --upgrade setuptools && \
pip install \
 pathlib \
 pathlib2 \
 # pycrypto \
 # cryptography \
 # packaging \
 # appdirs \
 # six \
 homeassistant

RUN \
mkdir ${HOME} -p && \
adduser -h ${HOME} -s /bin/bash -u 1001 -G root -D default && \

CMD haas --open-ui
# CMD [ "python", "-m", "homeassistant", "--config", "/config" ]
