###############################################################################
#
#           OpenMediaVault is a multifaceted NAS server software.
#
###############################################################################
FROM arm32v7/debian:jessie-slim

RUN apt-get update && apt-get install openmediavault
